apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twake-mail-frontend.fullname" . }}
  labels:
    {{- include "twake-mail-frontend.labels" . | nindent 4 }}
data:
  .env.js: |
    {{- include "twake-mail-frontend.envJs" . | nindent 4 }}
  appList.js: |
    {{- include "twake-mail-frontend.appListJs" . | nindent 4 }}
