{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "twake-mail-frontend.fullname" . }}
  labels:
    {{- include "twake-mail-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $.Values.ingress.jmap.enabled }}
          {{- range $.Values.ingress.jmap.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.ingress.jmap.service.name }}
                port:
                  number: {{ $.Values.ingress.jmap.service.port }}
          {{- end }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "twake-mail-frontend.fullname" $ }}
                port:
                  name: http
    {{- end }}
{{- end }}
